### ISSUE TITLE
Edge case when scan type is ignored

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#300]
http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=1614

With this yaml, the assessor unexpectedly runs for cases where `assr_ma/scan_t1` is something other than what is listed for `scan_t1.types`. I.e. `scan_t1.types` seems to be getting ignored here.

```
inputs:
  xnat:
    scans:
      - name: scan_fmri
        types: fmri_rest_*
      - name: scan_t1
        types: T1_tr8_te4,T1_tr8_te4_short,T1_tr9_te5
        select: from(assr_ma/scan_t1)
    assessors:
      - name: assr_ma
        proctypes: slant_gpu_v1
```
